// import './startup/initDatabase';
import '../app/aws-s3';
import '../app/predict';
import '../app/setting';
import '../app/api';
import './publications/cases';
import './publications/submit';
import './publications/userData';
import './publications/users';
import './startup/onCreateUser';
import './startup/initSetting';
